---
title: "house price pred"
author: "Brahimi Hachem"
date: "2024-10-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


## Setups :
```{r}
library(tidyverse)
library(tidymodels)
library(ggcorrplot)
```

```{r}
house_train <- read_csv("C:/Users/Hachem Brahimi/Desktop/Last Data/kaggle comp/kaggle-comp-/house price/train.csv")
house_test <- read_csv("C:/Users/Hachem Brahimi/Desktop/Last Data/kaggle comp/kaggle-comp-/house price/test.csv")
ss<- read_csv("C:/Users/Hachem Brahimi/Desktop/Last Data/kaggle comp/kaggle-comp-/house price/sample_submission.csv")
```

```{r}
house_train %>% glimpse()
```

```{r}
house_train %>% select(where(is.character)) %>% is.na() %>% colSums()
```

```{r}
house_train %>% select(where(is.double)) %>% is.na() %>% colSums()
```


### No cleaning is done :
```{r}
df1<- house_train %>% 
  select(!where(is.character)) %>% 
  select(-c(Id,LotFrontage,MasVnrArea,GarageYrBlt)) #%>% 
 # is.na() %>% 
 # colSums()


#i decided to avoid dealing with the missing values in the columns that have a lot of missing values and charecter columns 
```

```{r}
df1 %>% glimpse()
```

```{r}
corr<- df1 %>% cor(use="pairwise.complete.obs")
corr %>% ggcorrplot::ggcorrplot(type = "lower", lab = T,lab_size = 2, colors = c("blue", "white", "red"), title = "Correlation plot of the variables",tl.cex = 7,digits = 1) -> corr_plot 



plotly::ggplotly(corr_plot)
```

```{r}
le_df <- df1 %>%
  select(c("OverallQual","1stFlrSF","GrLivArea","FullBath","GarageCars","GarageArea","SalePrice")) 
  
```

## Modelisation :

### linear reg model :
```{r}
lr_model <- linear_reg() %>% set_engine("lm") 
```

```{r}
lr_rec <- le_df %>% recipe(SalePrice ~ .) %>% 
  step_impute_mean(all_numeric_predictors()) %>% 
  step_normalize(all_numeric_predictors())
```

```{r}
lr_wf <- workflow() %>% add_model(lr_model) %>% add_recipe(lr_rec)
```

```{r}
lr_fit <- lr_wf %>% fit(data = le_df)
```

```{r}
lr_fit %>% pull_workflow_fit() %>% tidy()
```

```{r}
lr_fit %>% predict(new_data = house_test) -> predictions 
ss$SalePrice <- predictions$.pred
```



### Random forest model :
```{r}
rf_mod<- rand_forest(mtry = tune(),trees = tune(),min_n = tune()) %>% 
  set_engine("ranger") %>% 
  set_mode("regression")
```

```{r}
rf_grid <- grid_regular(mtry(range = c(3,6)),
                        trees(range = c(1000,2000)),
                        min_n(range = c(2,20)),
                        levels = 3)
ctrl <- control_grid(verbose = TRUE)
metric <- metric_set(rmse)
rf_folds <- vfold_cv(le_df,v = 5)

```

```{r}
rf_rec <- le_df %>% recipe(SalePrice ~ .) %>% 
  step_impute_mean(all_numeric_predictors()) %>% 
  step_normalize(all_numeric_predictors())
```

```{r}
rf_wf <- workflow() %>% add_model(rf_mod) %>% add_recipe(rf_rec)
```

```{r}
rf_tune <- tune_grid(rf_wf, resamples = rf_folds, grid = rf_grid, control = ctrl,metrics = metric)
```

```{r}
rf_tune %>% collect_metrics() %>% arrange(-mean)
```
```{r}
rf_best <- rand_forest(mtry = 6,trees = 1000,min_n=2) %>% 
  set_engine("ranger") %>% 
  set_mode("regression")
```

```{r}
rfb_wf <- workflow() %>% add_model(rf_best) %>% add_recipe(rf_rec)
```

```{r}
rfb_fit <- rfb_wf %>% fit(data = le_df)
```

```{r}
rfb_fit %>% predict(new_data = house_test) -> predictions
ss$SalePrice <- predictions$.pred
```

```{r}
write_csv(ss,"C:/Users/Hachem Brahimi/Desktop/Last Data/kaggle comp/kaggle-comp-/house price/submission.csv")
```

